title:   Li Xie
logo: "/images/Profile.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm  a Senior Data Analyst based in Toronto, responsible for data analytic tasks, experience in the Telecom and Finance industries.
  <br><br>
  Perceptive and logical professional with proven ability to communicate with both technical professionals and end users to identify and translate business requirements. Proven ability to work with talented professionals to develop valuable process solutions to meet business objectives. 
  <br><br>
  <a href="www.linkedin.com/in/li-xie-b3a772203">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/li.xie4008">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.notion.so/lixie/About-Me-Li-Xie-60aa825369154277b3fbc5ca3c39fef8">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal
 
